# Generated by Django 5.0.7 on 2024-09-11 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='user_firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
