# Generated by Django 5.0.7 on 2024-09-11 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablelist', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('booktable_id', models.AutoField(primary_key=True, serialize=False)),
                ('booktable_date', models.DateField()),
                ('booktable_time', models.TimeField()),
                ('booktable_guests', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelist.tablelist')),
            ],
        ),
    ]
